/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mx.grupogateway.view;

import com.formdev.flatlaf.FlatDarkLaf;
import com.mx.grupogateway.excel.ExcelController;
import com.mx.grupogateway.user.User;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;

/**
 *
 * @author Eduardo Reyes Hernández
 */
public class ImportarExcel extends javax.swing.JFrame {

    private static final String MESSAGE_STATUS_FILE = "Ningún archivo ha sido seleccionado.";
    private User user;

    /**
     * Creates new form Facturacion
     */
    public ImportarExcel() {
        initComponents();
        iniciarProcesos();
    }

    private void iniciarProcesos() {
        cargarIconoVentana();
        nombreArchivo.setText(MESSAGE_STATUS_FILE);
        botonImportarExcel.setVisible(false);
    }

    private void cargarIconoVentana() {
        Image excelIconImage = Toolkit.getDefaultToolkit().getImage(
                ClassLoader.getSystemResource("Imagenes/icons8-microsoft-excel-2019-48.png")
        );
        setIconImage(excelIconImage);
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Se encarga de abrir el explorador de archivos específicos de Excel,
     * posteriormente importa la información en una Lista de objetos Excel
     * mientras informa al user el progreso.
     */
    private void exportDataCellFromExcelFileToDataBase() {
        ExcelController excelController;
        if (!nombreArchivo.getText().equals(MESSAGE_STATUS_FILE)) {
            excelController = new ExcelController(nombreArchivo.getText(), progressBar, tituloStatus);
            excelController.executeExcelSwingWorkers();
            botonImportarExcel.setVisible(false);
            nombreArchivo.setText(MESSAGE_STATUS_FILE);
        }
    }

    private void selectExcelFile() {
        ExcelFileChooser excelFileChooser = new ExcelFileChooser();
        if (excelFileChooser.isAnyFileSelected()) {
            nombreArchivo.setText(excelFileChooser.getFilePath());
            botonImportarExcel.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloSeleccionArchivo = new javax.swing.JLabel();
        botonExaminarArchivo = new javax.swing.JButton();
        indicadorArchivo = new javax.swing.JLabel();
        nombreArchivo = new javax.swing.JLabel();
        botonImportarExcel = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        tituloStatus = new javax.swing.JLabel();
        textoProgreso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Importar hoja de Excel");
        setIconImage(getIconImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tituloSeleccionArchivo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tituloSeleccionArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloSeleccionArchivo.setText("Seleccione el archivo Excel:");

        botonExaminarArchivo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        botonExaminarArchivo.setText("Examinar...");
        botonExaminarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonExaminarArchivoMouseClicked(evt);
            }
        });

        indicadorArchivo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        indicadorArchivo.setText("Archivo Seleccionado:");

        nombreArchivo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        botonImportarExcel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        botonImportarExcel.setText("Importar a la Base de Datos");
        botonImportarExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonImportarExcelMouseClicked(evt);
            }
        });

        progressBar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        progressBar.setStringPainted(true);

        tituloStatus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tituloStatus.setText("Status:");

        textoProgreso.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textoProgreso.setText("Info");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tituloSeleccionArchivo)
                                .addGap(18, 18, 18)
                                .addComponent(botonExaminarArchivo))
                            .addComponent(indicadorArchivo)
                            .addComponent(nombreArchivo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(botonImportarExcel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tituloStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoProgreso)))
                        .addGap(0, 214, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloSeleccionArchivo)
                    .addComponent(botonExaminarArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(indicadorArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(botonImportarExcel)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloStatus)
                    .addComponent(textoProgreso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonImportarExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImportarExcelMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            exportDataCellFromExcelFileToDataBase();
        }
    }//GEN-LAST:event_botonImportarExcelMouseClicked

    private void botonExaminarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExaminarArchivoMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            selectExcelFile();
        }
    }//GEN-LAST:event_botonExaminarArchivoMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        evt.getID();

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Facturacion facturacion = new Facturacion();
        facturacion.setUser(user);
        facturacion.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ImportarExcel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonExaminarArchivo;
    private static javax.swing.JButton botonImportarExcel;
    private javax.swing.JLabel indicadorArchivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreArchivo;
    private static javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel textoProgreso;
    private javax.swing.JLabel tituloSeleccionArchivo;
    private javax.swing.JLabel tituloStatus;
    // End of variables declaration//GEN-END:variables
}
