/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mx.grupogateway.view;

import com.formdev.flatlaf.FlatDarkLaf;
import com.mx.grupogateway.employee.Employee;
import com.mx.grupogateway.employee.EmployeeController;
import com.mx.grupogateway.employee.category.EmployeeCategory;
import com.mx.grupogateway.user.User;
import com.mx.grupogateway.util.ValidacionJPasswordField;
import com.mx.grupogateway.util.FondoLogin;
import com.mx.grupogateway.util.IconoVentana;
import com.mx.grupogateway.util.ValidacionPassword;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo Reyes Hernández
 */
public class Login extends javax.swing.JFrame {

    private EmployeeController employeeController;
    protected Optional<Employee> optionalEmployee;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        iniciarProcesos();
    }

    private void iniciarProcesos() {
        cargarIconoVentana();
        employeeController = new EmployeeController();
        campoUsuario.requestFocus();
    }

    private void cargarIconoVentana() {
        this.setIconImage(IconoVentana.getIconoVentana());
    }

    /**
     * Realiza el llamado de la ventana que corresponda a la categoría del
     * optionalEmployee.
     *
     * @param idCategoria Identificador de categoría obtenido de la BD.
     */
    private void validarCategoria(EmployeeCategory employeeCategory) {
        switch (employeeCategory) {
            case ADMINISTRADOR:
                Gestion gestion = new Gestion();
                gestion.setUser(optionalEmployee.get().getUser());
                gestion.setVisible(true);
                break;
            case FACTURACION:
                Facturacion facturacion = new Facturacion();
                facturacion.setUser(optionalEmployee.get().getUser());
                facturacion.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Lo sentimos, pero el cargo "
                        + "de este empleado no fue encontrado.",
                        "Cargo no existe.",
                        JOptionPane.INFORMATION_MESSAGE
                );
                break;
        }
        dispose();
    }

    /**
     * Toma el nombre del usuario y la contraseña para posteriormente,
     * consultarlos en la BD y de ser validos consultar los identificadores
     * (Categoría y User) a los que corresponde.
     */
    private void validarPerfilUsuario() {
        String nombreUsuario = campoUsuario.getText();
        User usuario = new User();
        usuario.setPassword(campoPassword.getPassword(), false);
        usuario.setUserName(nombreUsuario);
        optionalEmployee = employeeController.getEmployeeIdentifiersByUserAutenticated(usuario);
        if (!optionalEmployee.isPresent()) {
            JOptionPane.showMessageDialog(null,
                    "El usuario o la contraseña son incorrectos.");
        } else {
            validarCategoria(optionalEmployee.get().getEmployeeCategory());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoLogin();
        enterpriseIcon = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        campoPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        checkBox = new javax.swing.JCheckBox();
        statusPassword = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        registerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setResizable(false);

        enterpriseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.png"))); // NOI18N

        campoUsuario.setBackground(new Color(0, 0, 0, 0));
        campoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        campoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        campoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        campoUsuario.setCaretColor(new java.awt.Color(0, 0, 0));

        jSeparator1.setBackground(new Color(0, 0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        campoPassword.setBackground(new Color(0, 0, 0, 0));
        campoPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        campoPassword.setForeground(new java.awt.Color(0, 0, 0));
        campoPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        campoPassword.setCaretColor(new java.awt.Color(0, 0, 0));
        campoPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPasswordKeyReleased(evt);
            }
        });

        jSeparator2.setBackground(new Color(0, 0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        checkBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojoCerrado.png"))); // NOI18N
        checkBox.setRolloverEnabled(false);
        checkBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojoAbierto.png"))); // NOI18N
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });

        botonIngresar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        registerLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(0, 0, 0));
        registerLabel.setText("Registrarse");
        registerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enterpriseIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 434, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botonIngresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerLabel))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(enterpriseIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(checkBox)
                        .addGap(13, 13, 13)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusPassword)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIngresar)
                    .addComponent(registerLabel))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        evt.getID();
        ValidacionJPasswordField.visualizacionPassword(
                checkBox, campoPassword
        );
    }//GEN-LAST:event_checkBoxActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        evt.getID();
        if (ValidacionPassword.esPasswordValida(campoPassword.getPassword())) {
            validarPerfilUsuario();
        } else {
            JOptionPane.showMessageDialog(null, "Favor de ingresar una contraseña válida.",
                    "Contraseña incorrecta",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void registerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            new Registro().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_registerLabelMouseClicked

    private void campoPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER
                && ValidacionPassword.esPasswordValida(campoPassword.getPassword())) {
            botonIngresar.doClick();
        }
    }//GEN-LAST:event_campoPasswordKeyPressed

    private void campoPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPasswordKeyReleased
        evt.getID();
        ValidacionJPasswordField.evaluarCampoPassword(campoPassword, statusPassword);
    }//GEN-LAST:event_campoPasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JLabel enterpriseIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel statusPassword;
    // End of variables declaration//GEN-END:variables
}
