/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mx.grupogateway.system.view;

import com.formdev.flatlaf.FlatDarkLaf;
import com.mx.grupogateway.system.controller.ExcelController;
import com.mx.grupogateway.system.modelo.Excel;
import com.mx.grupogateway.system.modelo.Proyecto;
import com.mx.grupogateway.system.view.util.ExcelFileChooser;
import java.awt.event.MouseEvent;
import java.util.LinkedList;
import javax.swing.JFileChooser;

/**
 *
 * @author Eduardo Reyes Hernández
 */
public class ImportarExcel extends javax.swing.JFrame {

    private static Excel excel;
    private ExcelController excelController;
    private static LinkedList<Proyecto> listaProyectos;

    /**
     * Creates new form Facturacion
     */
    public ImportarExcel() {
        initComponents();
        lockButtonImportExcel();
    }

    private void lockButtonImportExcel() {
        if (listaProyectos == null) {
            botonImportarExcel.setVisible(false);
        } else {
            botonImportarExcel.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloSeleccionArchivo = new javax.swing.JLabel();
        botonExaminarArchivo = new javax.swing.JButton();
        indicadorArchivo = new javax.swing.JLabel();
        nombreArchivo = new javax.swing.JLabel();
        botonImportarExcel = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        tituloStatus = new javax.swing.JLabel();
        textoProgreso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Importar hoja de Excel");
        setResizable(false);

        tituloSeleccionArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloSeleccionArchivo.setText("Seleccione el archivo Excel:");

        botonExaminarArchivo.setText("Examinar...");
        botonExaminarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonExaminarArchivoMouseClicked(evt);
            }
        });

        indicadorArchivo.setText("Archivo Seleccionado:");

        nombreArchivo.setText("Ningun archivo seleccionado");

        botonImportarExcel.setText("Importar a la Base de Datos");
        botonImportarExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonImportarExcelMouseClicked(evt);
            }
        });

        progressBar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        progressBar.setStringPainted(true);

        tituloStatus.setText("Status:");

        textoProgreso.setText("Info");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tituloSeleccionArchivo)
                                .addGap(18, 18, 18)
                                .addComponent(botonExaminarArchivo))
                            .addComponent(indicadorArchivo)
                            .addComponent(nombreArchivo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(botonImportarExcel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tituloStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoProgreso)))
                        .addGap(0, 219, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloSeleccionArchivo)
                    .addComponent(botonExaminarArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(indicadorArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(botonImportarExcel)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloStatus)
                    .addComponent(textoProgreso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonImportarExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImportarExcelMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (listaProyectos != null) {
                excelController = new ExcelController(listaProyectos,
                        progressBar, textoProgreso
                );
                excelController.getExecuteSwingWorker();
                listaProyectos = null;
                lockButtonImportExcel();
            }
        }
    }//GEN-LAST:event_botonImportarExcelMouseClicked

    private void botonExaminarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExaminarArchivoMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            ExcelFileChooser excelFileChooser = new ExcelFileChooser(
                    new JFileChooser(".")
            );
            if (!excelFileChooser.getRutaArchivo().isEmpty()) {
                nombreArchivo.setText(excelFileChooser.getRutaArchivo());
                excel = new Excel(excelFileChooser.getRutaArchivo(),
                        excelFileChooser.getOptionValueSelected(),
                        progressBar, textoProgreso
                );
                excel.execute();
                listaProyectos = excel.getDatos();
                lockButtonImportExcel();
            }
        }
    }//GEN-LAST:event_botonExaminarArchivoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ImportarExcel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonExaminarArchivo;
    private static javax.swing.JButton botonImportarExcel;
    private javax.swing.JLabel indicadorArchivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreArchivo;
    private static javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel textoProgreso;
    private javax.swing.JLabel tituloSeleccionArchivo;
    private javax.swing.JLabel tituloStatus;
    // End of variables declaration//GEN-END:variables
}
